### ISSUE TITLE
Bug: Does not match recursive profile URLs

### ISSUE THREAD

**Issue by LeviSnoot** [Lartsch/FediFollow-Chrome#1]
First of all, thank you for making this extension. It's the only one of its kind I can find that actually does what I want it to. Great work!

Before I follow someone I like to browse the profiles media tab, and see who they're following etc.
The issue I'm running into here is the extension does not match URLs underneath the path `https://instance.xyz/@username`

So for example `https://instance.xyz/@username/media`, `https://instance.xyz/@username/following` etc. don't work.

I believe it should be a fairly simple regex fix but I'm not confident I'll be able to fix it myself which is why I'm not making a PR. However I tested the following [string on regex101](https://regex101.com/r/Za6OnZ/2) and it appears to match everything we want.

```regex
/(http|https):\/\/.*\/@.*/gim
```

![image](https://user-images.githubusercontent.com/13402525/205337000-9c009410-e279-4c4a-861a-f8d0d2b9db77.png)

**Comment by Lartsch** [comment]
Hi!
Fixed in the latest update :)
I also noticed it while working on the latest update... Now found your issue.

Thanks for creating the issue.

**Comment by Lartsch** [comment]
btw., that's the regex if you want to try it out

const followPageRegex = /^(https?:\/\/(www\.)?.*\..*?\/)((@\w+(@([\w-]+\.)+?\w+)?)|explore|following|followers)\/?(\d+)?\/?$/;
