### ISSUE TITLE
Enhancement: Add support for bookmarking, replying

### ISSUE THREAD

**Issue by LeviSnoot** [Lartsch/FediFollow-Chrome#2]
As a feature enhancement I would love to see this project work with post interactions such as _Favourite_, _Boost_, _Reply_ and _Bookmark_.

**Comment by LeviSnoot** [comment]
I can see this marked as done in planned features (which I admit should've read before creating this issue), however it does not appear to work for me so I guess this is a bug instead of an enhancement.

**Comment by Lartsch** [comment]
Hi!

Please check out the latest update. The ext. now supports:
- Showing toot status on external instances (faved, reblogged)
- Showing "Following" on external instances
- Toot interactions (fav, reblog)
- Single click to interact only, double click to interact + redirect (you can turn off auto-action)

I will add support for bookmarking soon. I will also look into replying.

**Comment by Lartsch** [comment]
Bookmarking will be added tomorrow or Monday at latest.

**Comment by Lartsch** [comment]
Releases 0.8.2 and 0.8.3 have added support for bookmarking and replying
